version: '2'

services:
  php:
    build: .
    volumes:
      - .:/app
    links:
      - rabbitmq

  rabbitmq:
    image: bitnami/rabbitmq:3.7
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.backup/rabbitmq/rabbitmq-tutorial:/bitnami
